src/Entity/Intervention.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InterventionRepository")
 * @ORM\Table(name="tbl_intervention")
 */
class Intervention
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_depot;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_restitution;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $session_user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $password;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\OS", inversedBy="Intervention")
     * @ORM\JoinColumn(nullable=false)
     */
    private $OS;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Equipment", inversedBy="intervention")
     * @ORM\JoinColumn(nullable=false)
     */
    private $equipment;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EquipmentIncomplete", mappedBy="intervention")
     */
    private $equipmentIncompletes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Technician", mappedBy="intervention")
     */
    private $technicians;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Observation", mappedBy="intervention", cascade={"persist", "remove"})
     */
    /* private $observation;*/
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="intervention")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\TypeIntervention", mappedBy="intevention_typeIntervention", cascade={"persist"})
     */
    private $typeInterventions;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Observation;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Status", inversedBy="status")
     */
    private $status;




    public function __construct()
    {
        $this->equipmentIncompletes = new ArrayCollection();
        $this->technicians = new ArrayCollection();
        $this->typeInterventions = new ArrayCollection();
        $this->statuses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDepot(): ?\DateTimeInterface
    {
        return $this->date_depot;
    }

    public function setDateDepot(\DateTimeInterface $date_depot): self
    {
        $this->date_depot = $date_depot;

        return $this;
    }

    public function getDateRestitution(): ?\DateTimeInterface
    {
        return $this->date_restitution;
    }

    public function setDateRestitution(\DateTimeInterface $date_restitution): self
    {
        $this->date_restitution = $date_restitution;

        return $this;
    }

    public function getSessionUser(): ?string
    {
        return $this->session_user;
    }

    public function setSessionUser(?string $session_user): self
    {
        $this->session_user = $session_user;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getOS(): ?OS
    {
        return $this->OS;
    }

    public function setOS(?OS $OS): self
    {
        $this->OS = $OS;

        return $this;
    }

    public function getEquipment(): ?Equipment
    {
        return $this->equipment;
    }

    public function setEquipment(?Equipment $equipment): self
    {
        $this->equipment = $equipment;

        return $this;
    }


    /**
     * @return Collection|EquipmentIncomplete[]
     */
    public function getEquipmentIncompletes(): Collection
    {
        return $this->equipmentIncompletes;
    }

    public function addEquipmentIncomplete(EquipmentIncomplete $equipmentIncomplete): self
    {
        if (!$this->equipmentIncompletes->contains($equipmentIncomplete)) {
            $this->equipmentIncompletes[] = $equipmentIncomplete;
            $equipmentIncomplete->addIntervention($this);
        }

        return $this;
    }

    public function removeEquipmentIncomplete(EquipmentIncomplete $equipmentIncomplete): self
    {
        if ($this->equipmentIncompletes->contains($equipmentIncomplete)) {
            $this->equipmentIncompletes->removeElement($equipmentIncomplete);
            $equipmentIncomplete->removeIntervention($this);
        }

        return $this;
    }

    /**
     * @return Collection|Technician[]
     */
    public function getTechnicians(): Collection
    {
        return $this->technicians;
    }

    public function addTechnician(Technician $technician): self
    {
        if (!$this->technicians->contains($technician)) {
            $this->technicians[] = $technician;
            $technician->addIntervention($this);
        }

        return $this;
    }

    public function removeTechnician(Technician $technician): self
    {
        if ($this->technicians->contains($technician)) {
            $this->technicians->removeElement($technician);
            $technician->removeIntervention($this);
        }

        return $this;
    }

    /* public function getObservation(): ?Observation
    {
        return $this->observation;
    }

    public function setObservation(?Observation $observation): self
    {
        $this->observation = $observation;

        // set (or unset) the owning side of the relation if necessary
        $newIntervention = null === $observation ? null : $this;
        if ($observation->getIntervention() !== $newIntervention) {
            $observation->setIntervention($newIntervention);
        }

        return $this;
    }*/

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection|TypeIntervention[]
     */
    public function getTypeInterventions(): Collection
    {
        return $this->typeInterventions;
    }

    public function addTypeIntervention(TypeIntervention $typeIntervention): self
    {
        if (!$this->typeInterventions->contains($typeIntervention)) {
            $this->typeInterventions[] = $typeIntervention;
            $typeIntervention->addInteventionTypeIntervention($this);
        }

        return $this;
    }

    public function removeTypeIntervention(TypeIntervention $typeIntervention): self
    {
        if ($this->typeInterventions->contains($typeIntervention)) {
            $this->typeInterventions->removeElement($typeIntervention);
            $typeIntervention->removeInteventionTypeIntervention($this);
        }

        return $this;
    }

    public function getObservation(): ?string
    {
        return $this->Observation;
    }

    public function setObservation(?string $Observation): self
    {
        $this->Observation = $Observation;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }
    
}

src/Form/InterventionType.php
<?php

namespace App\Form;

use App\Entity\Technician;
use App\Entity\Intervention;
use App\Entity\TypeIntervention;
use App\Entity\EquipmentIncomplete;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class InterventionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('client')   
            ->add('date_depot')
            ->add('date_restitution')  
            ->add('equipment') 
        ;

        $builder->add('equipmentIncompletes', EntityType::class, array(
            'class' => EquipmentIncomplete::class,
            'by_reference' => false,
            'choice_label' => 'name',
            'multiple' => true,
        ));

        $builder
      
        ->add('session_user')
        ->add('password')
        ->add('OS') 
        ;

        $builder->add('typeInterventions', EntityType::class, array(
            'class' => TypeIntervention::class,
            'by_reference' => false,
            'choice_label' => 'name',
            'multiple' => true,
        ));

        $builder
    
        ->add('observation')
        ;

        $builder->add('technicians', EntityType::class, array(
            'class' => Technician::class,
            'by_reference' => false,
            'choice_label' => 'firstname',
            'multiple' => true,
        ));

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Intervention::class,
        ]);
    }
}

src/Controller/InterventionController.php
<?php

namespace App\Controller;

use App\Entity\Intervention;
use App\Entity\Equipment;
use App\Entity\Observation;
use App\Form\InterventionType;
use App\Repository\InterventionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/intervention")
 */
class InterventionController extends AbstractController
{
    /**
     * @Route("/", name="intervention_index", methods={"GET"})
     */
    public function index(InterventionRepository $interventionRepository): Response
    {
        return $this->render('intervention/index.html.twig', [
            'interventions' => $interventionRepository->findAll(),
            'Number' => $interventionRepository->nbr(),
        ]);
    }

    /**
     * @Route("/new", name="intervention_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $intervention = new Intervention();

        $form = $this->createForm(InterventionType::class, $intervention);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($intervention);
            $entityManager->flush();

            return $this->redirectToRoute('intervention_index');
        }

        return $this->render('intervention/new.html.twig', [
            'intervention' => $intervention,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="intervention_show", methods={"GET"})
     */
    public function show(Intervention $intervention): Response
    {
        return $this->render('intervention/show.html.twig', [
            'interventions' => $intervention,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="intervention_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Intervention $intervention): Response
    {
        $form = $this->createForm(InterventionType::class, $intervention);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('intervention_index');
        }

        return $this->render('intervention/edit.html.twig', [
            'intervention' => $intervention,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="intervention_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Intervention $intervention): Response
    {
        if ($this->isCsrfTokenValid('delete'.$intervention->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($intervention);
            $entityManager->flush();
        }

        return $this->redirectToRoute('intervention_index');
    }

     /**
     * @Route("/{id}/intervention", name="client_index_filter")
     */
    public function filter($id ,InterventionRepository $interventionRepository): Response
    {
        $interventions = $interventionRepository->findBy(['status' => $id]);

        dump($interventions);

        return $this->render('intervention/index.html.twig', [
            // 'interventions' => $interventionRepository->filter($id),
            'interventions' => $interventions,
        ]);
    }



}

templates/intervention/_delete_form.html.twig
<form method="post" action="{{ path('intervention_delete', {'id': intervention.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ intervention.id) }}">
    <button class="btn">Delete</button>
</form>

templates/intervention/_form.html.twig
<style>

    .big_div{
         background-color: #9DD2CB;
         height : 75%;
         width : 100%;
         padding : 16px;
         margin-top : 16px;
    }

    .width{
        width : 45%;
        height : 38px;
    }
</style>

    <div class="big_div">
        <p>Client</p>
        {{ form_widget(form.client) }}
    <hr>
        <div style="float:right"> Date de RESTITUTION </div>
        <div>Date de DEPOT </div>

        <div style="float:right">{{ form_widget(form.date_restitution) }}</div>
        <div >{{ form_widget(form.date_depot) }}</div>
        

    <hr>
        <div style="height:130px;">
            <div style="float:right">  Le matériel est t'il incomplet ?  </div>
            <div> MATERIEL</div>

            <div class="width" style="float:right"> {{ form_widget(form.equipmentIncompletes) }}  </div>
            <div class="width">{{ form_widget(form.equipment) }}</div>
        </div>
    <hr>
        <p>Système d'exploitation du PC</p>
         {{ form_widget(form.OS) }}
    <hr>

        <div style="float:right">  Mot de passe de session   </div>
        <div> Session utilisateur </div>

        <div class="width" style="float:right"> {{ form_widget(form.password) }}  </div>
        <div class="width">{{ form_widget(form.session_user) }}</div>

    <hr>
        <p>Type d'intervention</p>
         {{ form_widget(form.typeInterventions) }}
    <hr>
         <p>Observation</p>
         {{ form_widget(form.observation) }}
    <hr>
        <p>Technicien</p>
         {{ form_widget(form.technicians) }}
    
</div> 

<div style="margin-top : 16px;">
 <center>
    <button class="btn btn-success"> Ajouter la demande<br>&<br>IMPRIMER la fiche</button>
 </center>
</div>

templates/intervention/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Intervention{% endblock %}

{% block body %}
    <h1>Edit Intervention</h1>

    {{ include('intervention/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('intervention_index') }}">back to list</a>

    {{ include('intervention/_delete_form.html.twig') }}
{% endblock %}

templates/intervention/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Intervention index{% endblock %}

{% block body %}

<style>

    .container{
        display: contents;

    }

    .filtreTd{
        border-right:1px solid black;
    }

    .filtreTd:hover{
        border-right:1px solid black;
        background-color: #343a40;
        color:white;
    }

    .filtre{
        width: 100%;
        text-align: center;
        height : 50px;
    }
    
</style>
<table class="filtre">
    <tr>
        <td class="filtreTd"><a href="{{ path('client_index_filter', {'id': '1'} ) }}">Demande en cours</a>  </td>
        <td class="filtreTd"><a href="{{ path('client_index_filter', {'id': '2'} ) }}"> Intervention en cour</a></td>
        <td class="filtreTd"><a href="{{ path('client_index_filter', {'id': '3'} ) }}">Intervention en attente</a></td>
        <td class="filtreTd"><a href="{{ path('client_index_filter', {'id': '4'} ) }}"> >50 dernières intervention</a></td>
    </tr>
</table>

<table class="table">
  <thead class="thead-dark">
    <tr>
        <th scope="col">Date_depot</th>
        <th scope="col">Client</th>
        <th scope="col">Interventions</th>
         <!-- <th scope="col">Date_restitution</th>
        <th scope="col">Session_user</th>
        <th scope="col">Password</th> 
        <th scope="col">OS</th>-->
        <th scope="col">Equipement</th>
        <th scope="col">Equipement Incomplet</th>
        <th scope="col">Technicien</th>
        <th scope="col" style="text-align:center">Administration</th>
        
        
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for intervention in interventions %}
            <tr>
                <td>{{ intervention.dateDepot ? intervention.dateDepot|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ intervention.client }}</td>
                <!-- <td>{{ intervention.dateRestitution ? intervention.dateRestitution|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ intervention.sessionUser }}</td>
                <td>{{ intervention.password }}</td> 
                <td>{{ intervention.OS }}</td>-->

                {% if  intervention.equipment  == 'Pc fixe' %}

                <td style="background : #FFCDCD">{{ intervention.equipment }}</td>

                {% else %}

                <td style="background : #FFFF71">{{ intervention.equipment }}</td>

                {% endif %}

                <td>
                {% for intervention in intervention.typeInterventions %}

                        {% if  intervention.name   == 'Depanage' %}
                                <p style="background : #5698DC">{{ intervention.name }}</p>
                        {% elseif  intervention.name   == 'Formatage' %}
                                <p style="background : black; color: white">{{ intervention.name }}</p>
                        {% elseif  intervention.name   == 'Autres' %}
                                <p style="background : #88D96E">{{ intervention.name }}</p>
                        {% endif %}
                {% endfor %}
                </td>
                
                <td>
                {% for intervention in intervention.equipmentIncompletes %}
                                {{ intervention.name }}
                    {% endfor %}
                </td>
                <td>
                {% for intervention in intervention.technicians %}
                                {{ intervention.firstname }}
                {% endfor %}
                </td>
                
                <td>
                     <center>
                        <a href="{{ path('intervention_show', {'id': intervention.id}) }}"><button type="button" class="btn btn-primary">Voir <br> Intervention</button></a>
                        <a href="{{ path('intervention_edit', {'id': intervention.id}) }}"><button type="button" class="btn btn-danger">Modifier <br> Intervention</button></a>
                        <a href="{{ path('pdf', {'id': intervention.id}) }}"><button type="button" class="btn btn-info"><i class="fas fa-print"></i> <br> Imprimer</button></a>
                    </center>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
    </tr>
  </tbody>
</table>

    <a href="{{ path('intervention_new') }}">Create new</a>
{% endblock %}

templates/intervention/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Intervention{% endblock %}

{% block body %}

<style>
    h1{
        text-align : center;
        margin-top : 16px;
    }
</style>

    <h1>Intervention à effectuer</h1>

    {{ include('intervention/_form.html.twig') }}

    <a href="{{ path('intervention_index') }}">back to list</a>
{% endblock %}

templates/intervention/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Intervention{% endblock %}

{% block body %}
    <h1>Intervention</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ interventions.id }}</td>
            </tr>
            <tr>
                <th>Date_depot</th>
                <td>{{ interventions.dateDepot ? interventions.dateDepot|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_restitution</th>
                <td>{{ interventions.dateRestitution ? interventions.dateRestitution|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Session_user</th>
                <td>{{ interventions.sessionUser }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ interventions.password }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('intervention_index') }}">back to list</a>

    <a href="{{ path('intervention_edit', {'id': interventions.id}) }}">edit</a>

{% endblock %}